// Game data: jobs, abilities, equipment, battles, story, errands.
// Condensed but faithful adaptation of the FFT PS1 content list
// (see COMPLETION_REPORT.md for the guide record mapping).

export const ELEMENTS = ['fire', 'ice', 'bolt', 'holy', 'none'];

export const JOBS = {
  squire: {
    id: 'squire', name: 'Squire', requires: null,
    desc: 'Balanced beginners. Fundaments: dash, shout, and steel.',
    move: 4, jump: 3, pa: 5, ma: 3, sp: 7, hp: 42, mp: 12,
    growth: { hp: 7, mp: 2, pa: 0.8, ma: 0.4, sp: 0.15 },
    equip: ['sword', 'dagger', 'shield', 'cloth', 'helm'],
    abilities: ['attack', 'rush', 'shout', 'potion_squire'],
  },
  chemist: {
    id: 'chemist', name: 'Chemist', requires: null,
    desc: 'Item-throwers. Guns aside, they keep the army alive.',
    move: 3, jump: 3, pa: 4, ma: 4, sp: 6, hp: 38, mp: 14,
    growth: { hp: 6, mp: 3, pa: 0.5, ma: 0.6, sp: 0.15 },
    equip: ['gun', 'dagger', 'cloth', 'hat'],
    abilities: ['attack', 'potion', 'hipotion', 'phoenix', 'antidote', 'ether', 'remedy', 'x_potion', 'elixir'],
  },
  knight: {
    id: 'knight', name: 'Knight', requires: { job: 'squire', jp: 200 },
    desc: 'Heavy steel. Breaks blades, shields, and helms.',
    move: 3, jump: 3, pa: 8, ma: 2, sp: 5, hp: 55, mp: 8,
    growth: { hp: 9, mp: 1, pa: 1.1, ma: 0.2, sp: 0.1 },
    equip: ['sword', 'shield', 'armor', 'helm'],
    abilities: ['attack', 'break_weapon', 'break_shield', 'break_helm', 'rend_mp'],
  },
  archer: {
    id: 'archer', name: 'Archer', requires: { job: 'squire', jp: 200 },
    desc: 'Longbows and height. Owns the high ground.',
    move: 3, jump: 3, pa: 6, ma: 2, sp: 6, hp: 42, mp: 8,
    growth: { hp: 7, mp: 1, pa: 0.9, ma: 0.2, sp: 0.2 },
    equip: ['bow', 'dagger', 'cloth', 'hat'],
    abilities: ['attack', 'aim_leg', 'aim_arm', 'charge'],
  },
  monk: {
    id: 'monk', name: 'Monk', requires: { job: 'squire', jp: 350 },
    desc: 'Bare fists that outpunch swords. Heals with chakra.',
    move: 4, jump: 4, pa: 9, ma: 3, sp: 7, hp: 52, mp: 12,
    growth: { hp: 8, mp: 2, pa: 1.0, ma: 0.4, sp: 0.2 },
    equip: ['fist', 'cloth', 'hat'],
    abilities: ['attack', 'pummel', 'chakra', 'revive_punch'],
  },
  thief: {
    id: 'thief', name: 'Thief', requires: { job: 'squire', jp: 350 },
    desc: 'Fast hands: gil, hearts, and helmets.',
    move: 4, jump: 4, pa: 5, ma: 3, sp: 9, hp: 40, mp: 10,
    growth: { hp: 6, mp: 2, pa: 0.7, ma: 0.4, sp: 0.35 },
    equip: ['dagger', 'sword', 'cloth', 'hat'],
    abilities: ['attack', 'steal_gil', 'steal_heart', 'steal_helm'],
  },
  blackmage: {
    id: 'blackmage', name: 'Black Mage', requires: { job: 'chemist', jp: 200 },
    desc: 'Black magicks: fire, ice, and lightning.',
    move: 3, jump: 3, pa: 2, ma: 9, sp: 5, hp: 34, mp: 26,
    growth: { hp: 5, mp: 5, pa: 0.2, ma: 1.2, sp: 0.1 },
    equip: ['rod', 'cloth', 'hat'],
    abilities: ['attack', 'fire', 'blizzard', 'thunder', 'flare'],
  },
  whitemage: {
    id: 'whitemage', name: 'White Mage', requires: { job: 'chemist', jp: 200 },
    desc: 'White magicks: cure wounds, mend faith, raise the fallen.',
    move: 3, jump: 3, pa: 2, ma: 8, sp: 6, hp: 36, mp: 26,
    growth: { hp: 5, mp: 5, pa: 0.2, ma: 1.1, sp: 0.12 },
    equip: ['rod', 'cloth', 'hat'],
    abilities: ['attack', 'cure', 'cura', 'raise', 'esuna', 'shell', 'regen'],
  },
  dragoon: {
    id: 'dragoon', name: 'Dragoon', requires: { job: 'thief', jp: 400 },
    desc: 'Spear-jumpers who strike from the sky.',
    move: 3, jump: 5, pa: 8, ma: 2, sp: 6, hp: 54, mp: 10,
    growth: { hp: 9, mp: 2, pa: 1.1, ma: 0.3, sp: 0.15 },
    equip: ['spear', 'armor', 'helm', 'shield'],
    abilities: ['attack', 'jump_strike', 'pierce'],
  },
  summoner: {
    id: 'summoner', name: 'Summoner', requires: { job: 'blackmage', jp: 500 },
    desc: 'Calls espers down on wide fields. Slow, vast, final.',
    move: 3, jump: 3, pa: 2, ma: 11, sp: 4, hp: 38, mp: 34,
    growth: { hp: 5, mp: 6, pa: 0.2, ma: 1.4, sp: 0.08 },
    equip: ['rod', 'cloth', 'hat'],
    abilities: ['attack', 'ifrit', 'shiva', 'ramuh'],
  },
  timemage: {
    id: 'timemage', name: 'Time Mage', requires: { job: 'blackmage', jp: 250 },
    desc: 'Bends the clock: haste, slow, stop, and falling stars.',
    move: 3, jump: 3, pa: 2, ma: 9, sp: 6, hp: 34, mp: 28,
    growth: { hp: 5, mp: 5, pa: 0.2, ma: 1.2, sp: 0.12 },
    equip: ['rod', 'cloth', 'hat'],
    abilities: ['attack', 'haste', 'slow2', 'stop', 'meteor'],
  },
  ninja: {
    id: 'ninja', name: 'Ninja', requires: { job: 'thief', jp: 450 },
    desc: 'Fastest blade alive. Throws steel across the field.',
    move: 4, jump: 4, pa: 7, ma: 3, sp: 10, hp: 44, mp: 10,
    growth: { hp: 7, mp: 2, pa: 1.0, ma: 0.4, sp: 0.3 },
    equip: ['ninja', 'dagger', 'sword', 'cloth', 'hat'],
    abilities: ['attack', 'throw_knife', 'shuriken', 'shadowstrike'],
  },
  samurai: {
    id: 'samurai', name: 'Samurai', requires: { job: 'knight', jp: 450 },
    desc: 'Draws the iaido: ward, ruin, and restore in one breath.',
    move: 3, jump: 3, pa: 8, ma: 6, sp: 6, hp: 50, mp: 16,
    growth: { hp: 8, mp: 3, pa: 1.0, ma: 0.8, sp: 0.12 },
    equip: ['katana', 'sword', 'armor', 'helm'],
    abilities: ['attack', 'kiyomori', 'muramasa', 'murasame'],
  },
  geomancer: {
    id: 'geomancer', name: 'Geomancer', requires: { job: 'monk', jp: 300 },
    desc: 'The terrain itself answers: flame, stone, and undertow.',
    move: 3, jump: 3, pa: 7, ma: 5, sp: 6, hp: 48, mp: 14,
    growth: { hp: 8, mp: 3, pa: 0.9, ma: 0.7, sp: 0.12 },
    equip: ['sword', 'axe', 'shield', 'cloth', 'helm'],
    abilities: ['attack', 'flame_burst', 'rock_throw', 'undertow'],
  },
};

// kind: phys | magic | heal | revive | item | steal | buff | jump
// range: Manhattan tiles; aoe: 0 = single, 1 = plus, 2 = 3x3-ish radius
export const ABILITIES = {
  attack: { id: 'attack', name: 'Attack', kind: 'phys', range: 1, aoe: 0, power: 1.0, evade: true, sfx: 'hit', desc: 'Strike with the equipped weapon.' },
  rush: { id: 'rush', name: 'Rush', kind: 'phys', range: 1, aoe: 0, power: 0.8, evade: true, sfx: 'hit', desc: 'A quick shove: light damage, +10 CT to self.' },
  shout: { id: 'shout', name: 'Shout', kind: 'buff', range: 0, aoe: 0, power: 0, sfx: 'confirm', desc: 'Rally: +1 PA for 3 turns.' },
  potion_squire: { id: 'potion_squire', name: 'First Aid', kind: 'heal', range: 1, aoe: 0, power: 18, sfx: 'potion', desc: 'Field dressing: restore a little HP.' },
  potion: { id: 'potion', name: 'Potion', kind: 'item', range: 4, aoe: 0, power: 30, price: 50, sfx: 'potion', desc: 'Throw: restore 30 HP at range.' },
  hipotion: { id: 'hipotion', name: 'Hi-Potion', kind: 'item', range: 4, aoe: 0, power: 70, price: 150, sfx: 'potion', desc: 'Throw: restore 70 HP at range.' },
  phoenix: { id: 'phoenix', name: 'Phoenix Down', kind: 'revive', range: 4, aoe: 0, power: 25, price: 200, sfx: 'cure', desc: 'Throw: revive with 25% HP.' },
  antidote: { id: 'antidote', name: 'Antidote', kind: 'item', range: 4, aoe: 0, power: 0, price: 40, sfx: 'potion', desc: 'Throw: cure Poison.' },
  break_weapon: { id: 'break_weapon', name: 'Break: Weapon', kind: 'phys', range: 1, aoe: 0, power: 0.5, debuff: 'disarm', evade: true, sfx: 'hit', desc: 'Half damage and Disarm (2 turns).' },
  break_shield: { id: 'break_shield', name: 'Break: Shield', kind: 'phys', range: 1, aoe: 0, power: 0.5, debuff: 'exposed', evade: true, sfx: 'hit', desc: 'Half damage and Exposed: -evasion (3 turns).' },
  break_helm: { id: 'break_helm', name: 'Break: Helm', kind: 'phys', range: 1, aoe: 0, power: 0.6, debuff: 'daze', evade: true, sfx: 'hit', desc: 'Damage and Daze: -2 Speed (2 turns).' },
  rend_mp: { id: 'rend_mp', name: 'Rend MP', kind: 'phys', range: 2, aoe: 0, power: 0.3, drainMp: true, evade: true, sfx: 'hit', desc: 'Light damage and burn 12 MP.' },
  aim_leg: { id: 'aim_leg', name: 'Aim: Leg', kind: 'phys', range: 5, aoe: 0, power: 0.7, debuff: 'slow', evade: true, sfx: 'bow', desc: 'Bow shot that Slows (2 turns).' },
  aim_arm: { id: 'aim_arm', name: 'Aim: Arm', kind: 'phys', range: 5, aoe: 0, power: 0.7, debuff: 'disarm', evade: true, sfx: 'bow', desc: 'Bow shot that Disarms (2 turns).' },
  charge: { id: 'charge', name: 'Charge +2', kind: 'buff', range: 0, aoe: 0, power: 0, sfx: 'bow', desc: 'Next bow shot deals double damage.' },
  pummel: { id: 'pummel', name: 'Pummel', kind: 'phys', range: 1, aoe: 0, power: 1.3, evade: true, sfx: 'hit', desc: 'Heavy bare-handed blow.' },
  chakra: { id: 'chakra', name: 'Chakra', kind: 'heal', range: 0, aoe: 0, power: 35, sfx: 'cure', desc: 'Restore 35 HP and 8 MP to self.' },
  revive_punch: { id: 'revive_punch', name: 'Revive', kind: 'revive', range: 1, aoe: 0, power: 20, sfx: 'cure', desc: 'A shocking palm: revive adjacent ally at 20%.' },
  steal_gil: { id: 'steal_gil', name: 'Steal Gil', kind: 'steal', range: 1, aoe: 0, power: 0, steal: 'gil', sfx: 'gil', desc: 'Steal gil from the target.' },
  steal_heart: { id: 'steal_heart', name: 'Steal Heart', kind: 'steal', range: 3, aoe: 0, power: 0, steal: 'charm', sfx: 'confirm', desc: 'Charm: target skips its next turn.' },
  steal_helm: { id: 'steal_helm', name: 'Steal Helm', kind: 'steal', range: 1, aoe: 0, power: 0, steal: 'helm', sfx: 'confirm', desc: 'Steal a helm: target Exposed, gain 100 gil value.' },
  fire: { id: 'fire', name: 'Fire', kind: 'magic', element: 'fire', range: 4, aoe: 1, power: 1.1, mp: 6, ctr: 40, sfx: 'fire', desc: 'Fire damage, plus-shaped area.' },
  blizzard: { id: 'blizzard', name: 'Blizzard', kind: 'magic', element: 'ice', range: 4, aoe: 1, power: 1.1, mp: 6, ctr: 40, sfx: 'ice', desc: 'Ice damage, plus-shaped area.' },
  thunder: { id: 'thunder', name: 'Thunder', kind: 'magic', element: 'bolt', range: 4, aoe: 1, power: 1.1, mp: 6, ctr: 40, sfx: 'bolt', desc: 'Lightning damage, plus-shaped area.' },
  flare: { id: 'flare', name: 'Flare', kind: 'magic', element: 'none', range: 4, aoe: 0, power: 1.8, mp: 14, ctr: 60, sfx: 'fire', desc: 'Heavy non-elemental damage.' },
  cure: { id: 'cure', name: 'Cure', kind: 'heal', range: 4, aoe: 1, power: 1.0, mp: 6, ctr: 40, sfx: 'cure', desc: 'Restore HP, plus-shaped area.' },
  cura: { id: 'cura', name: 'Cura', kind: 'heal', range: 4, aoe: 1, power: 1.8, mp: 12, ctr: 50, sfx: 'cure', desc: 'Strong HP restore, plus-shaped area.' },
  raise: { id: 'raise', name: 'Raise', kind: 'revive', range: 4, aoe: 0, power: 30, mp: 10, ctr: 50, sfx: 'cure', desc: 'Revive at 30% HP.' },
  esuna: { id: 'esuna', name: 'Esuna', kind: 'heal', range: 4, aoe: 0, power: 0, mp: 6, ctr: 30, cleanse: true, sfx: 'cure', desc: 'Cure Poison, Slow, Daze, Disarm.' },
  jump_strike: { id: 'jump_strike', name: 'Jump', kind: 'jump', range: 4, aoe: 0, power: 1.6, evade: false, sfx: 'hit', desc: 'Leap skyward; land for heavy spear damage. Unavoidable.' },
  pierce: { id: 'pierce', name: 'Pierce', kind: 'phys', range: 2, aoe: 0, power: 1.1, evade: true, sfx: 'hit', desc: 'Long spear thrust, 2 tiles.' },
  ifrit: { id: 'ifrit', name: 'Ifrit', kind: 'magic', element: 'fire', range: 5, aoe: 2, power: 1.4, mp: 18, ctr: 70, sfx: 'fire', desc: 'Summon: great fire over a wide area.' },
  shiva: { id: 'shiva', name: 'Shiva', kind: 'magic', element: 'ice', range: 5, aoe: 2, power: 1.4, mp: 18, ctr: 70, sfx: 'ice', desc: 'Summon: great ice over a wide area.' },
  ramuh: { id: 'ramuh', name: 'Ramuh', kind: 'magic', element: 'bolt', range: 5, aoe: 2, power: 1.4, mp: 18, ctr: 70, sfx: 'bolt', desc: 'Summon: great lightning over a wide area.' },
  // time magic
  haste: { id: 'haste', name: 'Haste', kind: 'buff', range: 4, aoe: 1, status: 'haste', mp: 8, ctr: 40, sfx: 'confirm', desc: 'Allies act sooner: +3 Speed (3 turns).' },
  slow2: { id: 'slow2', name: 'Slow', kind: 'ailment', range: 4, aoe: 1, status: 'slow', mp: 8, ctr: 40, sfx: 'cancel', desc: 'Enemies drag: Slow (2 turns).' },
  stop: { id: 'stop', name: 'Stop', kind: 'ailment', range: 3, aoe: 0, status: 'stop', mp: 12, ctr: 50, sfx: 'cancel', desc: 'Freeze a foe solid (2 turns).' },
  meteor: { id: 'meteor', name: 'Meteor', kind: 'magic', element: 'none', range: 4, aoe: 2, power: 1.6, mp: 20, ctr: 70, sfx: 'bolt', desc: 'Call down falling stars, wide area.' },
  // ninja throw
  throw_knife: { id: 'throw_knife', name: 'Throw: Knife', kind: 'phys', range: 5, aoe: 0, power: 0.9, evade: true, sfx: 'bow', desc: 'Hurl a knife across the field.' },
  shuriken: { id: 'shuriken', name: 'Shuriken', kind: 'phys', range: 6, aoe: 0, power: 0.7, evade: true, sfx: 'bow', desc: 'Long star-throw, light damage.' },
  shadowstrike: { id: 'shadowstrike', name: 'Shadowstrike', kind: 'phys', range: 1, aoe: 0, power: 1.5, evade: true, sfx: 'hit', desc: 'Strike from the dark: heavy damage.' },
  // samurai draw out
  kiyomori: { id: 'kiyomori', name: 'Draw Out: Kiyomori', kind: 'buff', range: 3, aoe: 1, status: 'protect', mp: 8, ctr: 30, sfx: 'confirm', desc: 'Ward allies: halved physical damage (3 turns).' },
  muramasa: { id: 'muramasa', name: 'Draw Out: Muramasa', kind: 'iaido', element: 'none', range: 3, aoe: 0, power: 1.7, mp: 10, ctr: 40, sfx: 'hit', desc: 'Cursed draw: heavy MA-scaling damage.' },
  murasame: { id: 'murasame', name: 'Draw Out: Murasame', kind: 'heal', range: 3, aoe: 1, power: 1.4, mp: 10, ctr: 40, sfx: 'cure', desc: 'Soothing draw: restore allies HP.' },
  // geomancer elemental
  flame_burst: { id: 'flame_burst', name: 'Flame Burst', kind: 'magic', element: 'fire', range: 4, aoe: 1, power: 1.1, mp: 8, ctr: 40, sfx: 'fire', desc: 'The earth exhales fire.' },
  rock_throw: { id: 'rock_throw', name: 'Falling Rock', kind: 'magic', element: 'none', range: 4, aoe: 0, power: 1.4, mp: 6, ctr: 40, sfx: 'hit', desc: 'Drop a boulder on one foe.' },
  undertow: { id: 'undertow', name: 'Undertow', kind: 'magic', element: 'ice', range: 4, aoe: 1, power: 1.0, mp: 8, ctr: 40, sfx: 'ice', desc: 'Icy water drags foes down.' },
  // white magic, continued
  shell: { id: 'shell', name: 'Shell', kind: 'buff', range: 4, aoe: 1, status: 'shell', mp: 10, ctr: 40, sfx: 'confirm', desc: 'Ward allies: halved magic damage (3 turns).' },
  regen: { id: 'regen', name: 'Regen', kind: 'buff', range: 4, aoe: 1, status: 'regen', mp: 10, ctr: 40, sfx: 'cure', desc: 'Allies mend each turn (3 turns).' },
  // holy sword (Aveline)
  holy_hold: { id: 'holy_hold', name: 'Holy Sword: Hold', kind: 'ailment', element: 'holy', range: 3, aoe: 0, status: 'stop', mp: 10, ctr: 40, sfx: 'bolt', desc: 'Pin a foe with holy light (Stop).' },
  holy_blade: { id: 'holy_blade', name: 'Holy Sword: Blade', kind: 'phys', element: 'holy', range: 2, aoe: 0, power: 1.6, evade: true, sfx: 'hit', desc: 'A radiant two-tile slash.' },
  // limit (Cloud)
  braver: { id: 'braver', name: 'Limit: Braver', kind: 'phys', range: 1, aoe: 0, power: 1.8, evade: false, sfx: 'hit', desc: 'Leaping limit blow. Unavoidable.' },
  cross_slash: { id: 'cross_slash', name: 'Limit: Cross Slash', kind: 'phys', range: 1, aoe: 0, power: 1.1, debuff: 'slow', evade: true, sfx: 'hit', desc: 'Cross-cut that Slows.' },
  // chemist items, continued
  ether: { id: 'ether', name: 'Ether', kind: 'item', range: 4, aoe: 0, power: 30, restoreMp: true, price: 300, sfx: 'potion', desc: 'Throw: restore 30 MP.' },
  remedy: { id: 'remedy', name: 'Remedy', kind: 'item', range: 4, aoe: 0, power: 0, price: 250, cleanse: true, sfx: 'potion', desc: 'Throw: cure all ailments.' },
  x_potion: { id: 'x_potion', name: 'X-Potion', kind: 'item', range: 4, aoe: 0, power: 150, price: 500, sfx: 'potion', desc: 'Throw: restore 150 HP.' },
  elixir: { id: 'elixir', name: 'Elixir', kind: 'item', range: 4, aoe: 0, power: 999, price: 1000, sfx: 'potion', desc: 'Throw: fully restore HP.' },
  // enemy-only
  tail_swipe: { id: 'tail_swipe', name: 'Tail Swipe', kind: 'phys', range: 1, aoe: 0, power: 0.9, evade: true, sfx: 'hit', desc: 'Monster attack.' },
  goblin_punch: { id: 'goblin_punch', name: 'Goblin Punch', kind: 'phys', range: 1, aoe: 0, power: 1.0, evade: true, sfx: 'hit', desc: 'Gremlin fists.' },
  dark_holy: { id: 'dark_holy', name: 'Dark Holy', kind: 'magic', element: 'holy', range: 5, aoe: 1, power: 1.3, mp: 10, ctr: 50, sfx: 'bolt', desc: 'Wicked holy light.' },
  stone_gaze: { id: 'stone_gaze', name: 'Stone Gaze', kind: 'phys', range: 3, aoe: 0, power: 0.4, debuff: 'slow', evade: true, sfx: 'miss', desc: 'Petrifying look that slows.' },
  choco_attack: { id: 'choco_attack', name: 'Choco Attack', kind: 'phys', range: 1, aoe: 0, power: 1.2, evade: true, sfx: 'hit', desc: 'Furious beaking.' },
  choco_ball: { id: 'choco_ball', name: 'Choco Ball', kind: 'phys', range: 4, aoe: 0, power: 1.0, evade: true, sfx: 'bow', desc: 'A hurled chocobo egg.' },
  choco_cure: { id: 'choco_cure', name: 'Choco Cure', kind: 'heal', range: 3, aoe: 0, power: 1.2, sfx: 'cure', desc: 'Chocobo first aid.' },
  fire_breath: { id: 'fire_breath', name: 'Fire Breath', kind: 'magic', element: 'fire', range: 3, aoe: 1, power: 1.2, mp: 8, ctr: 40, sfx: 'fire', desc: 'Dragon breath.' },
  mind_blast: { id: 'mind_blast', name: 'Mind Blast', kind: 'ailment', range: 3, aoe: 0, status: 'sleep', sfx: 'cancel', desc: 'Psionic lullaby (Sleep).' },
  blood_suck: { id: 'blood_suck', name: 'Blood Suck', kind: 'phys', range: 1, aoe: 0, power: 0.8, drain: 0.5, evade: true, sfx: 'hit', desc: 'Feed and mend.' },
  triple_attack: { id: 'triple_attack', name: 'Triple Attack', kind: 'phys', range: 1, aoe: 0, power: 1.4, evade: true, sfx: 'hit', desc: 'Three heads strike as one.' },
};

export const EQUIPMENT = {
  // weapons
  dagger: { id: 'dagger', name: 'Dagger', slot: 'weapon', type: 'dagger', pa: 2, price: 120, desc: 'A small reliable blade.' },
  short_sword: { id: 'short_sword', name: 'Short Sword', slot: 'weapon', type: 'sword', pa: 4, price: 300, desc: 'Standard knightly sidearm.' },
  mythril_sword: { id: 'mythril_sword', name: 'Mythril Sword', slot: 'weapon', type: 'sword', pa: 6, price: 900, desc: 'Light, keen mythril edge.' },
  rune_blade: { id: 'rune_blade', name: 'Rune Blade', slot: 'weapon', type: 'sword', pa: 8, ma: 2, price: 2400, desc: 'A blade etched with glyphs.' },
  longbow: { id: 'longbow', name: 'Longbow', slot: 'weapon', type: 'bow', pa: 4, price: 400, desc: 'Reach out and touch someone.' },
  mythril_bow: { id: 'mythril_bow', name: 'Mythril Bow', slot: 'weapon', type: 'bow', pa: 7, price: 1400, desc: 'Sings when drawn.' },
  rod: { id: 'rod', name: 'Rod', slot: 'weapon', type: 'rod', ma: 3, price: 250, desc: 'Focus for magicks.' },
  mythril_rod: { id: 'mythril_rod', name: 'Mythril Rod', slot: 'weapon', type: 'rod', ma: 5, price: 1200, desc: 'Hums with stored spells.' },
  spear: { id: 'spear', name: 'Spear', slot: 'weapon', type: 'spear', pa: 6, price: 800, desc: 'Long reach, cold point.' },
  spark_gun: { id: 'spark_gun', name: 'Spark Gun', slot: 'weapon', type: 'gun', pa: 5, price: 1100, desc: 'Goug machinist work. Never misses short range.' },
  // offhand / armor
  buckler: { id: 'buckler', name: 'Buckler', slot: 'offhand', type: 'shield', evade: 8, price: 200, desc: 'Small shield, +8 evade.' },
  mythril_shield: { id: 'mythril_shield', name: 'Mythril Shield', slot: 'offhand', type: 'shield', evade: 14, price: 1000, desc: '+14 evade.' },
  linen: { id: 'linen', name: 'Linen Robe', slot: 'body', type: 'cloth', hp: 8, price: 150, desc: '+8 HP.' },
  mythril_armor: { id: 'mythril_armor', name: 'Mythril Armor', slot: 'body', type: 'armor', hp: 22, price: 1300, desc: '+22 HP.' },
  cloth_hat: { id: 'cloth_hat', name: 'Cloth Hat', slot: 'head', type: 'hat', mp: 8, price: 150, desc: '+8 MP.' },
  mythril_helm: { id: 'mythril_helm', name: 'Mythril Helm', slot: 'head', type: 'helm', hp: 12, price: 800, desc: '+12 HP.' },
  // accessories
  leather_boots: { id: 'leather_boots', name: 'Leather Boots', slot: 'acc', move: 1, price: 600, desc: '+1 Move.' },
  magic_ring: { id: 'magic_ring', name: 'Magic Ring', slot: 'acc', ma: 2, price: 900, desc: '+2 MA.' },
  power_wrist: { id: 'power_wrist', name: 'Power Wrist', slot: 'acc', pa: 2, price: 900, desc: '+2 PA.' },
  // consumables
  potion_item: { id: 'potion_item', name: 'Potion', slot: 'item', ability: 'potion', price: 50, desc: 'Restores 30 HP.' },
  hipotion_item: { id: 'hipotion_item', name: 'Hi-Potion', slot: 'item', ability: 'hipotion', price: 150, desc: 'Restores 70 HP.' },
  phoenix_item: { id: 'phoenix_item', name: 'Phoenix Down', slot: 'item', ability: 'phoenix', price: 200, desc: 'Revives a KO ally.' },
  antidote_item: { id: 'antidote_item', name: 'Antidote', slot: 'item', ability: 'antidote', price: 40, desc: 'Cures Poison.' },
  ether_item: { id: 'ether_item', name: 'Ether', slot: 'item', ability: 'ether', price: 300, desc: 'Restores 30 MP.' },
  remedy_item: { id: 'remedy_item', name: 'Remedy', slot: 'item', ability: 'remedy', price: 250, desc: 'Cures all ailments.' },
  x_potion_item: { id: 'x_potion_item', name: 'X-Potion', slot: 'item', ability: 'x_potion', price: 500, desc: 'Restores 150 HP.' },
  elixir_item: { id: 'elixir_item', name: 'Elixir', slot: 'item', ability: 'elixir', price: 1000, desc: 'Fully restores HP.' },
  // chapter 3+ wares
  knight_sword: { id: 'knight_sword', name: 'Knight Sword', slot: 'weapon', type: 'sword', pa: 10, price: 5000, desc: 'A lordly blade, heavy and true.' },
  ninja_knife: { id: 'ninja_knife', name: 'Ninja Knife', slot: 'weapon', type: 'ninja', pa: 6, price: 1500, desc: 'Silent, balanced for throwing.' },
  short_katana: { id: 'short_katana', name: 'Short Katana', slot: 'weapon', type: 'katana', pa: 8, ma: 1, price: 2200, desc: 'A quick iaido blade.' },
  battle_axe: { id: 'battle_axe', name: 'Battle Axe', slot: 'weapon', type: 'axe', pa: 9, price: 1800, desc: 'Crude, heavy, final.' },
  hunting_bow: { id: 'hunting_bow', name: 'Hunting Bow', slot: 'weapon', type: 'bow', pa: 9, price: 2600, desc: 'For big game and bigger knights.' },
  feather_hat: { id: 'feather_hat', name: 'Feather Hat', slot: 'head', type: 'hat', mp: 12, price: 1200, desc: '+12 MP.' },
  cachusha: { id: 'cachusha', name: 'Cachusha', slot: 'head', type: 'hat', mp: 16, hp: 8, price: 2500, desc: '+16 MP, +8 HP.' },
  wizard_robe: { id: 'wizard_robe', name: 'Wizard Robe', slot: 'body', type: 'cloth', mp: 16, price: 1800, desc: '+16 MP.' },
  rubber_costume: { id: 'rubber_costume', name: 'Rubber Costume', slot: 'body', type: 'cloth', hp: 20, price: 2200, desc: '+20 HP. Squeaks.' },
  feather_mantle: { id: 'feather_mantle', name: 'Feather Mantle', slot: 'acc', evade: 10, price: 1500, desc: '+10 evade.' },
  dracula_mantle: { id: 'dracula_mantle', name: 'Dracula Mantle', slot: 'acc', pa: 2, evade: 6, price: 3000, desc: '+2 PA, +6 evade.' },
  defense_ring: { id: 'defense_ring', name: 'Defense Ring', slot: 'acc', hp: 15, price: 2000, desc: '+15 HP.' },
  barette: { id: 'barette', name: 'Barette', slot: 'acc', ma: 2, mp: 8, price: 2800, desc: '+2 MA, +8 MP.' },
};

// height maps use single chars; legend per battle (h = height, w = water/blocked)
function H(rows) { return rows; }

export const BATTLES = [
  {
    id: 'b1_orbonne', name: 'Orbonne Monastery', chapter: 1, boss: false, music: 'battle',
    brief: 'Cadets on patrol: brigands raid the monastery stores. Drive them off.',
    objective: 'Defeat all enemies. Keep Rowan alive.',
    deployMax: 3, gil: 200,
    map: {
      w: 8, d: 8, theme: 'monastery',
      heights: H(['11111111', '11122111', '11122111', '11111111', '11111111', '11222111', '11111111', '11111111']),
    },
    player: [{ x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 }],
    enemies: [
      { job: 'squire', name: 'Brigand', x: 2, y: 1, level: 1 },
      { job: 'squire', name: 'Brigand', x: 4, y: 1, level: 1 },
      { job: 'archer', name: 'Poacher', x: 6, y: 2, level: 1 },
    ],
    treasure: [{ x: 6, y: 6, item: 'potion_item' }],
    hidden: [{ x: 0, y: 0, item: 'potion_item' }],
  },
  {
    id: 'b2_dorter', name: 'Dorter Trade City', chapter: 1, boss: false, music: 'battle',
    brief: 'A cardinal\'s men shake down the markets. Hold the square.',
    objective: 'Defeat all enemies.',
    deployMax: 4, gil: 350,
    map: { w: 9, d: 8, theme: 'town', heights: H(['111111111', '122111211', '122111211', '111111111', '111111111', '121111121', '111111111', '111111111']) },
    player: [{ x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 }, { x: 7, y: 6 }],
    enemies: [
      { job: 'knight', name: 'Temple Knight', x: 4, y: 1, level: 3 },
      { job: 'archer', name: 'Temple Bowman', x: 2, y: 2, level: 2 },
      { job: 'archer', name: 'Temple Bowman', x: 6, y: 2, level: 2 },
      { job: 'chemist', name: 'Temple Medic', x: 4, y: 3, level: 2 },
    ],
    treasure: [{ x: 0, y: 0, item: 'phoenix_item' }],
  },
  {
    id: 'b3_sweegy', name: 'Sweegy Woods', chapter: 1, boss: false, music: 'battle',
    brief: 'Goblins nest in the wood. Clear the road for the supply carts.',
    objective: 'Defeat all monsters.',
    deployMax: 4, gil: 300,
    map: { w: 9, d: 9, theme: 'woods', heights: H(['111111111', '111111111', '112111211', '112111211', '111111111', '111111111', '211111112', '111111111', '111111111']) },
    player: [{ x: 1, y: 7 }, { x: 3, y: 7 }, { x: 5, y: 7 }, { x: 7, y: 7 }],
    enemies: [
      { monster: 'goblin', name: 'Goblin', x: 2, y: 1, level: 3 },
      { monster: 'goblin', name: 'Goblin', x: 4, y: 1, level: 3 },
      { monster: 'goblin', name: 'Goblin', x: 6, y: 1, level: 4 },
      { monster: 'bomb', name: 'Red Bomb', x: 4, y: 3, level: 4 },
    ],
    treasure: [{ x: 8, y: 4, item: 'hipotion_item' }],
    hidden: [{ x: 4, y: 4, item: 'antidote_item' }],
  },
  {
    id: 'b4_thieves', name: 'Thieves Fort', chapter: 1, boss: false, music: 'battle',
    brief: 'The woodland fort shelters the goblin-smugglers. Roust them.',
    objective: 'Defeat all enemies.',
    deployMax: 4, gil: 400,
    map: { w: 9, d: 8, theme: 'woods', heights: H(['111111111', '111111111', '112111211', '112111211', '111111111', '111111111', '111111111', '111111111']) },
    player: [{ x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 }, { x: 7, y: 6 }],
    enemies: [
      { job: 'thief', name: 'Fort Rogue', x: 2, y: 1, level: 4 },
      { job: 'thief', name: 'Fort Rogue', x: 4, y: 1, level: 4 },
      { job: 'thief', name: 'Fort Rogue', x: 6, y: 1, level: 5 },
      { monster: 'goblin', name: 'Smuggler Pet', x: 4, y: 3, level: 5 },
    ],
    treasure: [{ x: 8, y: 7, item: 'phoenix_item' }],
    hidden: [{ x: 0, y: 0, item: 'power_wrist' }],
  },
  {
    id: 'b4_lenalia', name: 'Lenalia Plateau', chapter: 2, boss: false, music: 'battle',
    brief: 'Windmill militia block the pass. Take the high ground first.',
    objective: 'Defeat all enemies.',
    deployMax: 4, gil: 450,
    map: { w: 9, d: 9, theme: 'plateau', heights: H(['333333333', '333222333', '332222233', '322111223', '321111123', '321111123', '322111223', '332222233', '333333333']) },
    player: [{ x: 3, y: 7 }, { x: 4, y: 7 }, { x: 5, y: 7 }, { x: 4, y: 6 }],
    enemies: [
      { job: 'archer', name: 'Militia Bowman', x: 4, y: 0, level: 5 },
      { job: 'archer', name: 'Militia Bowman', x: 2, y: 1, level: 5 },
      { job: 'knight', name: 'Militia Blade', x: 4, y: 2, level: 6 },
      { job: 'blackmage', name: 'Hedge Wizard', x: 6, y: 1, level: 5 },
    ],
    treasure: [{ x: 0, y: 4, item: 'leather_boots' }],
  },
  {
    id: 'b_zirekile', name: 'Zirekile Falls', chapter: 2, boss: false, music: 'battle',
    brief: 'Rogue mages dam the falls to flood the low road. Break the dam-ward.',
    objective: 'Defeat all enemies.',
    deployMax: 4, gil: 550,
    map: { w: 9, d: 9, theme: 'aqueduct', heights: H(['111111111', '111010111', '111010111', '111010111', '111111111', '111010111', '111010111', '111010111', '111111111']) },
    player: [{ x: 1, y: 8 }, { x: 3, y: 8 }, { x: 5, y: 8 }, { x: 7, y: 8 }],
    enemies: [
      { job: 'blackmage', name: 'Dam Warden', x: 4, y: 1, level: 6 },
      { job: 'whitemage', name: 'Dam Warden', x: 4, y: 3, level: 6 },
      { job: 'archer', name: 'Falls Bowman', x: 2, y: 1, level: 7 },
      { job: 'archer', name: 'Falls Bowman', x: 6, y: 1, level: 7 },
    ],
    treasure: [{ x: 8, y: 4, item: 'ether_item' }],
    hidden: [{ x: 0, y: 4, item: 'mythril_rod' }],
  },
  {
    id: 'b_golgorand', name: 'Golgorand Execution Site', chapter: 2, boss: false, music: 'battle',
    brief: 'Prisoners kneel at the block at dawn. The company arrives at midnight.',
    objective: 'Defeat all enemies.',
    deployMax: 4, gil: 650,
    map: { w: 10, d: 8, theme: 'town', heights: H(['1111111111', '1221111221', '1221111221', '1111111111', '1111111111', '1111111111', '1111111111', '1111111111']) },
    player: [{ x: 2, y: 6 }, { x: 4, y: 6 }, { x: 6, y: 6 }, { x: 8, y: 6 }],
    enemies: [
      { job: 'knight', name: 'Executioner', x: 4, y: 1, level: 8 },
      { job: 'knight', name: 'Executioner', x: 6, y: 1, level: 8 },
      { job: 'archer', name: 'Scaffold Guard', x: 5, y: 0, level: 7 },
      { job: 'monk', name: 'Scaffold Guard', x: 5, y: 2, level: 8 },
    ],
    treasure: [{ x: 0, y: 0, item: 'mythril_shield' }],
    hidden: [{ x: 9, y: 7, item: 'phoenix_item' }],
  },
  {
    id: 'b5_fovoham', name: 'Fovoham Plains', chapter: 2, boss: true, music: 'boss',
    brief: 'The Thunder Regent rides to crush the rebellion. End him.',
    objective: 'Defeat the Thunder Regent.',
    deployMax: 4, gil: 700, bossName: 'Thunder Regent',
    map: { w: 10, d: 8, theme: 'plains', heights: H(['1111111111', '1111111111', '1112222111', '1112222111', '1111111111', '1111111111', '1111111111', '1111111111']) },
    player: [{ x: 2, y: 6 }, { x: 4, y: 6 }, { x: 6, y: 6 }, { x: 8, y: 6 }],
    enemies: [
      { job: 'knight', name: 'Thunder Regent', boss: true, x: 5, y: 1, level: 10, abilities: ['attack', 'thunder', 'break_weapon'] },
      { job: 'monk', name: 'Regent Guard', x: 3, y: 2, level: 8 },
      { job: 'archer', name: 'Regent Bowman', x: 7, y: 2, level: 8 },
      { job: 'whitemage', name: 'Regent Cleric', x: 5, y: 3, level: 8 },
    ],
    treasure: [{ x: 9, y: 0, item: 'mythril_sword' }],
    hidden: [{ x: 0, y: 7, item: 'remedy_item' }],
  },
  {
    id: 'b6_lesalia', name: 'Lesalia Aqueducts', chapter: 3, boss: false, music: 'battle',
    brief: 'Through the undercity: thieves and worse nest below the capital.',
    objective: 'Defeat all enemies.',
    deployMax: 5, gil: 600,
    map: { w: 10, d: 9, theme: 'aqueduct', heights: H(['1111111111', '1111111111', '1110000111', '1110000111', '1110000111', '1110000111', '1111111111', '1111111111', '1111111111']) },
    player: [{ x: 1, y: 7 }, { x: 3, y: 7 }, { x: 5, y: 7 }, { x: 7, y: 7 }, { x: 9, y: 7 }],
    enemies: [
      { job: 'thief', name: 'Canal Rat', x: 2, y: 1, level: 10 },
      { job: 'thief', name: 'Canal Rat', x: 5, y: 1, level: 10 },
      { job: 'thief', name: 'Canal Rat', x: 8, y: 1, level: 11 },
      { monster: 'cactuar', name: 'Cactuar', x: 4, y: 4, level: 11 },
      { monster: 'cactuar', name: 'Cactuar', x: 6, y: 4, level: 11 },
    ],
    treasure: [{ x: 0, y: 0, item: 'power_wrist' }],
  },
  {
    id: 'b7_riovanes', name: 'Riovanes Castle', chapter: 3, boss: true, music: 'boss',
    brief: 'A duel on the ramparts. Rowan must face the Fell Knight alone... with friends below.',
    objective: 'Defeat the Fell Knight.',
    deployMax: 5, gil: 900, bossName: 'Fell Knight',
    map: { w: 9, d: 10, theme: 'castle', heights: H(['444444444', '444444444', '333333333', '333333333', '222222222', '222222222', '111111111', '111111111', '111111111', '111111111']) },
    player: [{ x: 2, y: 8 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 3, y: 9 }, { x: 5, y: 9 }],
    enemies: [
      { job: 'knight', name: 'Fell Knight', boss: true, x: 4, y: 1, level: 14, abilities: ['attack', 'dark_holy', 'break_helm'] },
      { job: 'dragoon', name: 'Wyvern Guard', x: 2, y: 2, level: 12 },
      { job: 'dragoon', name: 'Wyvern Guard', x: 6, y: 2, level: 12 },
      { job: 'summoner', name: 'Court Summoner', x: 4, y: 3, level: 12 },
    ],
    treasure: [{ x: 8, y: 9, item: 'mythril_armor' }],
    hidden: [{ x: 8, y: 0, item: 'ether_item' }],
  },
  {
    id: 'b_yardow', name: 'Yardow Fort City', chapter: 3, boss: false, music: 'battle',
    brief: 'The fort city changed flags overnight. Its new masters fight dirty.',
    objective: 'Defeat all enemies.',
    deployMax: 5, gil: 950,
    map: { w: 10, d: 9, theme: 'castle', heights: H(['2222222222', '2222222222', '2111111112', '2111111112', '2111111112', '2111111112', '2111111112', '2111111112', '1111111111']) },
    player: [{ x: 1, y: 7 }, { x: 3, y: 7 }, { x: 5, y: 7 }, { x: 7, y: 7 }, { x: 9, y: 7 }],
    enemies: [
      { job: 'ninja', name: 'Fort Shadow', x: 3, y: 2, level: 13 },
      { job: 'ninja', name: 'Fort Shadow', x: 7, y: 2, level: 13 },
      { job: 'thief', name: 'Turncoat', x: 5, y: 3, level: 12 },
      { job: 'timemage', name: 'Turncoat Mage', x: 5, y: 1, level: 13 },
    ],
    treasure: [{ x: 5, y: 0, item: 'ninja_knife' }],
    hidden: [{ x: 0, y: 8, item: 'x_potion_item' }],
  },
  {
    id: 'b8_limberry', name: 'Limberry Castle', chapter: 4, boss: false, music: 'battle',
    brief: 'The undercroft swarms. Push through to the holy vault.',
    objective: 'Defeat all enemies.',
    deployMax: 5, gil: 800,
    map: { w: 10, d: 10, theme: 'crypt', heights: H(['1111111111', '1111111111', '1121111211', '1121111211', '1111111111', '1111111111', '1121111211', '1121111211', '1111111111', '1111111111']) },
    player: [{ x: 1, y: 8 }, { x: 3, y: 8 }, { x: 5, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    enemies: [
      { monster: 'skeleton', name: 'Skeleton', x: 2, y: 1, level: 14 },
      { monster: 'skeleton', name: 'Skeleton', x: 5, y: 1, level: 14 },
      { monster: 'skeleton', name: 'Skeleton', x: 8, y: 1, level: 15 },
      { job: 'blackmage', name: 'Crypt Wizard', x: 3, y: 3, level: 15 },
      { job: 'whitemage', name: 'Crypt Cleric', x: 7, y: 3, level: 15 },
    ],
    treasure: [{ x: 5, y: 0, item: 'rune_blade' }],
  },
  {
    id: 'b_bethla', name: 'Bethla Garrison', chapter: 4, boss: false, music: 'battle',
    brief: 'The garrison holds the sluice road. Its sword-saints hold the bridge.',
    objective: 'Defeat all enemies.',
    deployMax: 5, gil: 1100,
    map: { w: 10, d: 9, theme: 'castle', heights: H(['1111111111', '1111111111', '1121111211', '1121111211', '1111111111', '1111111111', '1121111211', '1121111211', '1111111111']) },
    player: [{ x: 1, y: 8 }, { x: 3, y: 8 }, { x: 5, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    enemies: [
      { job: 'samurai', name: 'Bridge Saint', x: 4, y: 2, level: 16 },
      { job: 'samurai', name: 'Bridge Saint', x: 6, y: 2, level: 16 },
      { job: 'dragoon', name: 'Garrison Spear', x: 5, y: 1, level: 15 },
      { job: 'summoner', name: 'Garrison Caller', x: 5, y: 4, level: 15 },
    ],
    treasure: [{ x: 9, y: 0, item: 'short_katana' }],
    hidden: [{ x: 0, y: 8, item: 'remedy_item' }],
  },
  {
    id: 'b_igros', name: 'Igros Castle', chapter: 4, boss: false, music: 'battle',
    brief: 'The castle guard makes its last stand on the terraces — with red chocobos.',
    objective: 'Defeat all enemies.',
    deployMax: 5, gil: 1300,
    map: { w: 9, d: 10, theme: 'castle', heights: H(['111111111', '111111111', '222222222', '222222222', '333333333', '333333333', '222222222', '222222222', '111111111', '111111111']) },
    player: [{ x: 2, y: 8 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 3, y: 9 }, { x: 5, y: 9 }],
    enemies: [
      { job: 'geomancer', name: 'Terrace Warden', x: 3, y: 3, level: 17 },
      { job: 'geomancer', name: 'Terrace Warden', x: 6, y: 3, level: 17 },
      { job: 'knight', name: 'Castle Guard', x: 4, y: 5, level: 16 },
      { monster: 'red_chocobo', name: 'Red Chocobo', x: 5, y: 2, level: 16 },
    ],
    treasure: [{ x: 0, y: 0, item: 'cachusha' }],
    hidden: [{ x: 4, y: 0, item: 'elixir_item' }],
  },
  {
    id: 'b9_nelveska', name: 'Nelveska Temple', chapter: 4, boss: true, music: 'boss',
    brief: 'An ancient machina, Worker 7, guards the sky-ruin. Topple it.',
    objective: 'Defeat Worker 7.',
    deployMax: 5, gil: 1200, bossName: 'Worker 7',
    map: { w: 10, d: 10, theme: 'ruin', heights: H(['2222222222', '2111111112', '2111111112', '2111221112', '2111221112', '2111221112', '2111111112', '2111111112', '2111111112', '2222222222']) },
    player: [{ x: 2, y: 8 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 3, y: 9 }, { x: 7, y: 9 }],
    enemies: [
      { monster: 'worker7', name: 'Worker 7', boss: true, x: 5, y: 4, level: 19 },
      { monster: 'cockatrice', name: 'Cockatrice', x: 2, y: 2, level: 17 },
      { monster: 'cockatrice', name: 'Cockatrice', x: 8, y: 2, level: 17 },
    ],
    treasure: [{ x: 0, y: 0, item: 'magic_ring' }, { x: 9, y: 9, item: 'mythril_shield' }],
    hidden: [{ x: 5, y: 0, item: 'elixir_item' }],
  },
  {
    id: 'b_deathcity', name: 'Murond Death City', chapter: 4, boss: true, music: 'boss',
    brief: 'The dead city wakes. An elder dragon coils around the gate.',
    objective: 'Defeat the Elder Dragon.',
    deployMax: 5, gil: 1500, bossName: 'Elder Dragon',
    map: { w: 10, d: 10, theme: 'necropolis', heights: H(['1111111111', '1111111111', '1110000111', '1110000111', '1110000111', '1110000111', '1110000111', '1111111111', '1111111111', '1111111111']) },
    player: [{ x: 1, y: 8 }, { x: 3, y: 8 }, { x: 5, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    enemies: [
      { monster: 'dragon', name: 'Elder Dragon', boss: true, x: 5, y: 1, level: 19 },
      { monster: 'mindflare', name: 'Mindflare', x: 2, y: 1, level: 18 },
      { monster: 'mindflare', name: 'Mindflare', x: 8, y: 1, level: 18 },
      { monster: 'ghoul', name: 'Ghoul', x: 1, y: 3, level: 18 },
      { monster: 'ghoul', name: 'Ghoul', x: 9, y: 3, level: 18 },
    ],
    treasure: [{ x: 5, y: 9, item: 'dracula_mantle' }],
    hidden: [{ x: 0, y: 0, item: 'barette' }],
  },
  {
    id: 'b10_necropolis', name: 'Murond Necropolis', chapter: 4, boss: true, music: 'boss',
    brief: 'The last Zodiac stone burns below. End the Heritor and the war.',
    objective: 'Defeat the Heritor.',
    deployMax: 5, gil: 0, bossName: 'The Heritor',
    map: { w: 10, d: 10, theme: 'necropolis', heights: H(['1111111111', '1221111221', '1221111221', '1113333111', '1113333111', '1113333111', '1111111111', '1221111221', '1221111221', '1111111111']) },
    player: [{ x: 2, y: 8 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 3, y: 9 }, { x: 7, y: 9 }],
    enemies: [
      { job: 'summoner', name: 'The Heritor', boss: true, x: 5, y: 4, level: 21, abilities: ['attack', 'ifrit', 'shiva', 'ramuh', 'dark_holy'] },
      { monster: 'demon', name: 'Zodiac Warden', x: 3, y: 2, level: 19 },
      { monster: 'demon', name: 'Zodiac Warden', x: 7, y: 2, level: 19 },
      { job: 'knight', name: 'Oathsworn Blade', x: 5, y: 2, level: 18 },
    ],
    treasure: [],
  },
];

export const MONSTERS = {
  goblin: { pa: 6, ma: 1, sp: 6, hp: 30, mp: 0, move: 4, jump: 3, abilities: ['goblin_punch'], color: 0x4d9b4d },
  bomb: { pa: 7, ma: 5, sp: 5, hp: 34, mp: 10, move: 3, jump: 3, abilities: ['tail_swipe', 'fire'], color: 0xd24a2e },
  cactuar: { pa: 8, ma: 2, sp: 9, hp: 36, mp: 0, move: 4, jump: 3, abilities: ['goblin_punch'], color: 0x3f8f3f },
  skeleton: { pa: 9, ma: 2, sp: 6, hp: 55, mp: 0, move: 4, jump: 3, abilities: ['attack', 'break_weapon'], color: 0xd8d4c8 },
  cockatrice: { pa: 8, ma: 4, sp: 7, hp: 60, mp: 10, move: 5, jump: 4, abilities: ['tail_swipe', 'stone_gaze'], color: 0xc9a13b },
  worker7: { pa: 14, ma: 6, sp: 4, hp: 220, mp: 20, move: 2, jump: 2, abilities: ['attack', 'thunder', 'pummel'], color: 0x8a8f99, big: true },
  demon: { pa: 12, ma: 8, sp: 7, hp: 110, mp: 20, move: 4, jump: 3, abilities: ['attack', 'dark_holy'], color: 0x7a2e8f },
  chocobo: { pa: 7, ma: 3, sp: 8, hp: 40, mp: 10, move: 5, jump: 3, abilities: ['choco_attack', 'choco_cure'], color: 0xe8c83a },
  red_chocobo: { pa: 10, ma: 4, sp: 9, hp: 60, mp: 14, move: 5, jump: 4, abilities: ['choco_attack', 'choco_ball'], color: 0xc23a2e },
  panther: { pa: 9, ma: 1, sp: 10, hp: 44, mp: 0, move: 5, jump: 4, abilities: ['tail_swipe'], color: 0x3a3a4a },
  dragon: { pa: 12, ma: 6, sp: 5, hp: 120, mp: 20, move: 4, jump: 3, abilities: ['tail_swipe', 'fire_breath'], color: 0x3f7a3f, big: true },
  mindflare: { pa: 4, ma: 10, sp: 6, hp: 50, mp: 24, move: 3, jump: 3, abilities: ['mind_blast', 'thunder'], color: 0x8a5adf },
  ghoul: { pa: 8, ma: 4, sp: 5, hp: 60, mp: 10, move: 3, jump: 3, abilities: ['blood_suck', 'goblin_punch'], color: 0xb8c4b8 },
  hydra: { pa: 13, ma: 5, sp: 5, hp: 150, mp: 10, move: 3, jump: 3, abilities: ['triple_attack'], color: 0x2e8a7a, big: true },
};

// Poaching (guide: poaching record): monster family -> common / rare goods.
// Thieves always poach (25% rare); others find commons 30% of the time.
export const POACHES = {
  goblin: { common: 'potion_item', rare: 'hipotion_item' },
  bomb: { common: 'potion_item', rare: 'mythril_rod' },
  cactuar: { common: 'antidote_item', rare: 'leather_boots' },
  skeleton: { common: 'potion_item', rare: 'ether_item' },
  cockatrice: { common: 'antidote_item', rare: 'feather_mantle' },
  worker7: { common: 'hipotion_item', rare: 'spark_gun' },
  demon: { common: 'ether_item', rare: 'rune_blade' },
  chocobo: { common: 'phoenix_item', rare: 'hipotion_item' },
  red_chocobo: { common: 'remedy_item', rare: 'barette' },
  panther: { common: 'antidote_item', rare: 'leather_boots' },
  dragon: { common: 'hipotion_item', rare: 'defense_ring' },
  mindflare: { common: 'ether_item', rare: 'dracula_mantle' },
  ghoul: { common: 'ether_item', rare: 'ninja_knife' },
  hydra: { common: 'hipotion_item', rare: 'rubber_costume' },
};

// Propositions (guide: propositions record): dispatch a reserve unit for N
// completed battles; they return with gil, goods, and JP.
export const PROPOSITIONS = [
  { id: 'p1', name: 'Guard the Caravan', desc: 'Bandits on the Dorter road. Easy coin.', days: 1, minLevel: 1, gil: 300, items: ['potion_item'], jp: 30 },
  { id: 'p2', name: 'Cull the Direpack', desc: 'Wolves trouble the hamlets. Steel needed.', days: 2, minLevel: 5, gil: 600, items: ['hipotion_item'], jp: 60 },
  { id: 'p3', name: 'Survey the Sluice', desc: 'Map the flood tunnels below Lesalia.', days: 2, minLevel: 5, gil: 400, items: ['ether_item'], jp: 60 },
  { id: 'p4', name: 'Escort the Envoy', desc: 'A diplomat crosses the war zone. No mistakes.', days: 3, minLevel: 10, gil: 1000, items: ['phoenix_item'], jp: 100 },
  { id: 'p5', name: 'Delve the Deep Gate', desc: 'Something old stirs below Bethla.', days: 3, minLevel: 14, gil: 800, items: ['elixir_item'], jp: 120 },
];

export const HIRE_NAMES = ['Ash', 'Bly', 'Corv', 'Dain', 'Elswyth', 'Fen', 'Greta', 'Hob', 'Isolde', 'Joren', 'Kell', 'Liora', 'Marek', 'Nessa', 'Odo', 'Petra', 'Quinn', 'Rosalind', 'Sten', 'Tilda', 'Ulric', 'Vesper', 'Wystan', 'Ysolde'];

// Side content: tavern errands (dispatch-style bonus battles).
export const ERRANDS = [
  {
    id: 'e1_poach', name: 'Beast Hunt: Goblin Warren', requiresBattle: 2,
    desc: 'A hamlet pays for goblin pelts. (Poaching, condensed.)',
    battle: {
      id: 'e1_poach', name: 'Goblin Warren', chapter: 1, boss: false, music: 'battle',
      brief: 'Errand: clear the warren, keep the pelts.',
      objective: 'Defeat all monsters.', deployMax: 4, gil: 400,
      map: { w: 8, d: 8, theme: 'woods', heights: H(['11111111', '11111111', '11222111', '11222111', '11111111', '11111111', '11111111', '11111111']) },
      player: [{ x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 }, { x: 6, y: 6 }],
      enemies: [
        { monster: 'goblin', name: 'Goblin', x: 2, y: 1, level: 5 },
        { monster: 'goblin', name: 'Goblin', x: 4, y: 1, level: 5 },
        { monster: 'goblin', name: 'Goblin', x: 6, y: 1, level: 6 },
        { monster: 'panther', name: 'Dire Panther', x: 4, y: 2, level: 6 },
        { monster: 'bomb', name: 'Red Bomb', x: 5, y: 3, level: 6 },
      ],
      treasure: [{ x: 7, y: 0, item: 'hipotion_item' }],
    },
  },
  {
    id: 'e2_deep', name: 'Deep Delve: Sluice Depths', requiresBattle: 5,
    desc: 'Something nests in the floodgates. Bring antidotes.',
    battle: {
      id: 'e2_deep', name: 'Sluice Depths', chapter: 3, boss: false, music: 'battle',
      brief: 'Errand: purge the depths (Deep Dungeon, condensed).',
      objective: 'Defeat all monsters.', deployMax: 5, gil: 800,
      map: { w: 9, d: 9, theme: 'aqueduct', heights: H(['111111111', '111000111', '111000111', '111000111', '111000111', '111000111', '111000111', '111111111', '111111111']) },
      player: [{ x: 1, y: 7 }, { x: 3, y: 7 }, { x: 5, y: 7 }, { x: 7, y: 7 }, { x: 4, y: 7 }],
      enemies: [
        { monster: 'cockatrice', name: 'Cockatrice', x: 2, y: 1, level: 12 },
        { monster: 'skeleton', name: 'Drowned Bones', x: 4, y: 1, level: 12 },
        { monster: 'skeleton', name: 'Drowned Bones', x: 6, y: 1, level: 12 },
        { monster: 'cactuar', name: 'Cactuar', x: 4, y: 3, level: 12 },
      ],
      treasure: [{ x: 8, y: 8, item: 'mythril_rod' }],
    },
  },
  {
    id: 'e3_sky', name: 'Sky Pirate: Cloud\'s Debt', requiresBattle: 7,
    desc: 'A blond swordsman needs an escort — and his blade back.',
    battle: {
      id: 'e3_sky', name: 'Airship Graveyard', chapter: 4, boss: true, music: 'boss',
      brief: 'Errand: recruit the sky-pirate (secret character, condensed). Reward: Cloud joins!',
      objective: 'Defeat all enemies. Recruit Cloud.', deployMax: 5, gil: 500, recruit: 'Cloud',
      map: { w: 9, d: 9, theme: 'ruin', heights: H(['111111111', '111111111', '111222111', '111222111', '111222111', '111111111', '111111111', '111111111', '111111111']) },
      player: [{ x: 1, y: 7 }, { x: 3, y: 7 }, { x: 5, y: 7 }, { x: 7, y: 7 }, { x: 4, y: 7 }],
      enemies: [
        { job: 'thief', name: 'Sky Pirate', x: 4, y: 1, level: 14 },
        { job: 'thief', name: 'Sky Pirate', x: 2, y: 2, level: 14 },
        { job: 'archer', name: 'Sky Pirate', x: 6, y: 2, level: 14 },
        { monster: 'demon', name: 'Graveyard Warden', x: 4, y: 3, level: 14 },
      ],
      treasure: [{ x: 4, y: 0, item: 'mythril_bow' }],
    },
  },
];

export const RECRUIT_CLOUD = {
  name: 'Cloud', job: 'squire', level: 12,
  desc: 'Blond sky-pirate. Limitless attitude.',
};

export const RECRUIT_AVELINE = {
  name: 'Aveline', job: 'knight', level: 11,
  desc: 'Oathsworn holy blade, rescued at Lesalia.',
};

export const SHOP_STOCK = [
  'dagger', 'short_sword', 'longbow', 'rod', 'buckler', 'linen', 'cloth_hat',
  'potion_item', 'antidote_item', 'phoenix_item',
];
export const SHOP_STOCK_CH3 = ['mythril_sword', 'mythril_bow', 'mythril_rod', 'spear', 'spark_gun', 'mythril_shield', 'mythril_armor', 'mythril_helm', 'leather_boots', 'power_wrist', 'magic_ring', 'hipotion_item', 'ether_item', 'remedy_item', 'ninja_knife', 'battle_axe', 'feather_hat', 'wizard_robe', 'feather_mantle', 'defense_ring', 'short_katana'];
export const SHOP_STOCK_CH4 = ['knight_sword', 'hunting_bow', 'cachusha', 'rubber_costume', 'dracula_mantle', 'barette', 'x_potion_item', 'elixir_item'];

export const STORY = {
  intro: [
    'The Lion War has ended. The peace has not begun.',
    'Two lions circle the fallen crown of Crownfall — and in the monastery at Orbonne, a cadet named ROWAN copies scriptures while soldiers gather at the gate.',
    'What follows is a tale of stones that choose their bearers... and of the choice Rowan must make.',
  ],
  chapters: {
    1: 'Chapter 1 — The Fallen Cadet. Brigands, knights, and the first stone.',
    2: 'Chapter 2 — The Thunder Regent. The pass must be forced.',
    3: 'Chapter 3 — Blood Below Lesalia. The undercity remembers.',
    4: 'Chapter 4 — The Heritor. Every stone has a price.',
  },
  ending: [
    'The last stone goes dark. The Heritor is gone.',
    'No songs are sung for Rowan\'s company — history will credit the lions, as it always does.',
    'But in the villages along the road home, the wells are clean, the roads are safe, and the children play at knights with wooden swords.',
    'That is enough. That was always enough.',
    '— THE END —',
  ],
};
